name: Java8

on:
  push:
    paths:
      - '.github/workflows/java8.yml'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '45 */3 * * *'

jobs:
  java8-jdk:
    # internal comment counter: 100
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2016]
        update: [x, 282, 275, 272, 265, 262, 252, 242, 232, 222, 212, 202, 201, 192, 181, 172, 163, 162, 152, 144, 131, 121, 112, 102, 101, 92, 91, 72, 71]
        exclude:
          - os: ubuntu-18.04
            update: 101
        distro: [zulu, aoj, liberica]    
      fail-fast: false
      max-parallel: 6
    name: JDK 8.0.${{ matrix.update }}, ${{ matrix.os }}, ${{ matrix.distro }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK      
      uses: foojay2020/setup-java@adb2754170f8abe568d01d706a0927e606419852
      with:
        java-version: 8.0.${{ matrix.update }}
        distro: ${{ matrix.distro }}
    - name: java -version
      run: java -version
      
  java8-jdk-mac:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
        update: [x, 282, 275, 272, 265, 262, 252, 242, 232, 222, 212, 202, 201, 192, 181, 172, 163, 162, 152, 144, 131, 121, 112, 102, 92, 91, 72, 71, 66, 65, 60, 51, 45, 31, 25, 20, 11]
        distro: [zulu, aoj, liberica]
      fail-fast: false
      max-parallel: 5
    name: Mac-JDK 8.0.${{ matrix.update }}, ${{ matrix.os }}, ${{ matrix.distro }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: foojay2020/setup-java@adb2754170f8abe568d01d706a0927e606419852
      with:
        java-version: 8.0.${{ matrix.update }}
        distro: ${{ matrix.distro }}
    - name: java -version
      run: java -version

  java8-jre:
    # internal comment counter: 100
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2016, macOS-latest]
        update: [x, 282, 275, 272, 265, 262, 252, 242, 232, 222, 212]
        distro: [zulu, aoj, liberica]
      fail-fast: false
      max-parallel: 6
    name: JRE 8.0.${{ matrix.update }}, ${{ matrix.os }}, ${{ matrix.distro }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: foojay2020/setup-java@adb2754170f8abe568d01d706a0927e606419852
      with:
        java-package: jre
        java-version: 8.0.${{ matrix.update }}
        distro: ${{ matrix.distro }}
    - name: java -version
      run: java -version
