name: Java14

on:
  push:
    paths:
      - '*/*/java14.yml'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 */3 * * *'
      
jobs:
  java14:
    # internal comment counter: 100
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-latest, windows-2016]
        update: [x, 2, 1, 0]
      fail-fast: false
      max-parallel: 6
    name: JDK 14.0.${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK      
      uses: foojay2020/setup-java@adb2754170f8abe568d01d706a0927e606419852
      with:
        java-version: 14.0.${{ matrix.update }}
    - name: java -version
      run: java -version
