name: Java17

on:
  push:
    paths:
      - '*/*/java17.yml'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 */8 * * *'
      
jobs:
  java16:
    # internal comment counter: 103
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-latest, windows-2016]
        update: [17.0.0-ea, 17.0.0-ea.2, 17-ea]
      fail-fast: false
      max-parallel: 6
    name: JDK ${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: foojay2020/setup-java@adb2754170f8abe568d01d706a0927e606419852
      with:
        java-version: ${{ matrix.update }}
    - name: java -version
      run: java -version
