name: Java6g

on:
  push:
    paths:
      - '*/*/java6g.yml'

jobs:
  java6:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2016]
        update: [x, 77]
      fail-fast: false
      max-parallel: 6
    name: JDK 6.0.${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: foojay2020/setup-java@adb2754170f8abe568d01d706a0927e606419852
      with:
        java-version: 6.0.${{ matrix.update }}
    - name: java -version
      run: java -version
      