name: Java12

on:
  push:
    paths:
      - '*/*/java12.yml'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '32 */24 * * *'

jobs:
  java12:
    # internal comment counter: 100
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-latest, windows-2016]
        update: [x, 2, 1, 0]
      fail-fast: false
      max-parallel: 5
    name: JDK 12.0.${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: foojay2020/setup-java@adb2754170f8abe568d01d706a0927e606419852
      with:
        java-version: 12.0.${{ matrix.update }}
    - name: java -version
      run: java -version
